import { CalendarBlank, HandHeart, House, Leaf, Package, Scissors, Sparkle, Tag, UsersThree, Wrench, type Icon } from "@phosphor-icons/react";
import { composeListing, defaultSelections, taskTemplates, templateById } from "../taskCatalog";
import type { PostDraft, Task, TaskMode } from "./types";

/**
 * Seeded neighbors and listings. These stand in for a populated database so the
 * prototype has something to show before anyone has posted; a real listing from
 * Supabase flows through exactly the same `Task` shape.
 */

export const exampleTemplate = templateById("yard-lavender") ?? taskTemplates[0];
export const exampleSelections = defaultSelections(exampleTemplate);

export const initialPostDraft: PostDraft = {
  mode: "paid",
  templateId: exampleTemplate.id,
  selections: exampleSelections,
  customTitle: "",
  customDetails: "",
  customCategoryId: "home",
  customMinutes: 60,
  customCompletionId: "confirm",
  dateChoice: "Tomorrow",
  startTime: "10:00 AM",
  privateAddress: "214 Garden Walk",
  amount: String(composeListing(exampleTemplate, exampleSelections).suggestedPay),
  photoAcknowledged: false,
  photoPreview: "",
  riskConfirmed: false,
  safetyConfirmed: false,
};

export const tasks: Task[] = [
  {
    id: "leaves",
    title: "Front yard leaf cleanup",
    description: "Rake leaves and bag them for green bins.",
    mode: "sponsored",
    earning: 35,
    coords: { lat: 37.7792, lng: -122.2281 },
    areaId: "fruitvale",
    area: "Fruitvale",
    time: "Today · 3:00 PM",
    duration: "60–90 min",
    icon: Leaf,
    category: "Yard & garden",
    included: "Rake the front lawn and walkway; fill the provided green-waste bags",
    excluded: "No ladder, roof, gutters, tree trimming, hauling, or power tools",
    completion: "Front lawn and walkway are clear, bags are tied, and one privacy-safe final photo is added.",
    photo: "/assets/micro/front-yard-leaves.webp",
  },
  {
    id: "boxes",
    title: "Move two boxed lamps",
    description: "Carry two sealed boxes from the porch into the garage.",
    mode: "paid",
    earning: 18,
    coords: { lat: 37.8064, lng: -122.2934 },
    areaId: "westoak",
    area: "West Oakland",
    time: "Tomorrow · 10:00 AM",
    duration: "20–30 min",
    icon: Package,
    category: "Home help",
    included: "Carry two sealed lamp boxes from the porch into the garage",
    excluded: "No stairs, unpacking, furniture moving, or entry beyond the garage",
    completion: "Both sealed boxes are placed in the marked garage area without damage.",
  },
  {
    id: "tablet",
    title: "Set up a tablet for video calls",
    description: "Make the text larger and pin the video-call app to the home screen.",
    mode: "community",
    coords: { lat: 37.8362, lng: -122.2603 },
    areaId: "temescal",
    area: "Temescal",
    time: "Saturday · 11:00 AM",
    duration: "About 45 min",
    icon: UsersThree,
    category: "Tech help",
    included: "Increase text size and contrast; pin the video-call app to the home screen",
    excluded: "No passwords, purchases, account recovery, or access to private messages",
    completion: "June can read the larger text and open the pinned video-call app.",
  },
  {
    id: "pantry",
    title: "Pack pantry donation bags",
    description: "Sort shelf-stable groceries at the community center.",
    mode: "sponsored",
    earning: 24,
    coords: { lat: 37.7861, lng: -122.2401 },
    areaId: "fruitvale",
    area: "San Antonio",
    time: "Saturday · 9:30 AM",
    duration: "60 min",
    icon: HandHeart,
    youthEligible: true,
    category: "Community & mutual aid",
    included: "Sort shelf-stable groceries; pack labeled donation bags with staff present",
    excluded: "No driving, heavy lifting, food handling outside staff guidance, or private-home entry",
    completion: "Assigned bags are packed, counted, and checked by the pantry coordinator.",
  },
  {
    id: "hedge",
    title: "Trim a short front hedge",
    description: "Shape the waist-high hedge and sweep the walkway afterward.",
    mode: "paid",
    earning: 22,
    coords: { lat: 37.8442, lng: -122.2513 },
    areaId: "temescal",
    area: "Rockridge",
    time: "Sunday · 9:00 AM",
    duration: "45–60 min",
    icon: Scissors,
    category: "Yard & garden",
    included: "Shape the waist-high front hedge; sweep clippings from the walkway",
    excluded: "No ladder, chainsaw, power tool, or work above shoulder height",
    completion: "The hedge is evenly trimmed and the public walkway is clear.",
  },
  {
    id: "table",
    title: "Set up two folding tables",
    description: "Help a neighborhood group prepare a public-room craft table.",
    mode: "community",
    coords: { lat: 37.7649, lng: -122.2447 },
    areaId: "alameda",
    area: "Alameda",
    time: "Sunday · 1:00 PM",
    duration: "About 30 min",
    icon: House,
    category: "Community & mutual aid",
    included: "Unfold two lightweight tables; arrange chairs in the public craft room",
    excluded: "No vehicle use, lifting over 20 pounds, or private-room access",
    completion: "Two stable tables and the requested chairs are ready before the event.",
  },
  {
    id: "stoop",
    title: "Shovel a front stoop and stairs",
    description: "Clear overnight snow from the stairs and the walkway to the sidewalk.",
    mode: "paid",
    earning: 26,
    coords: { lat: 45.5231, lng: -73.5803 },
    areaId: "montreal",
    area: "Le Plateau-Mont-Royal",
    time: "Tomorrow · 8:00 AM",
    duration: "30–45 min",
    icon: House,
    category: "Home help",
    included: "Clear the exterior staircase and the walkway to the sidewalk; spread the provided salt",
    excluded: "No roof, balcony, ladder, or clearing a parked car",
    completion: "Stairs and walkway are clear and salted before the morning.",
  },
  {
    id: "brunch",
    title: "Set up chairs for a community brunch",
    description: "Help arrange tables and chairs in a neighbourhood community hall.",
    mode: "community",
    coords: { lat: 45.5232, lng: -73.6002 },
    areaId: "montreal",
    area: "Mile End",
    time: "Sunday · 10:00 AM",
    duration: "About 40 min",
    icon: UsersThree,
    category: "Community & mutual aid",
    included: "Unfold tables and arrange chairs in the main hall with an organizer present",
    excluded: "No food handling, vehicle use, or lifting over 20 pounds",
    completion: "The hall is arranged as the organizer requested before guests arrive.",
  },
];

export const sponsoredFixtureTask: Task = {
  id: "grocery-sponsored",
  title: "Grocery pickup for Ana",
  description: "Pick up a prepaid grocery order and carry it to the front door.",
  mode: "sponsored",
  earning: 24,
  coords: { lat: 37.7703, lng: -122.2534 },
  areaId: "alameda",
  area: "Alameda West End",
  time: "Saturday · 2:00 PM",
  duration: "About 45 min",
  icon: Package,
  category: "Errands & pickup",
  included: "Collect the prepaid order and carry the bags to the front door.",
  excluded: "No purchasing, substitutions, or entry into the home.",
  completion: "Order is delivered to the front door and confirmed in the task thread.",
};

export const pastThreadTasks: Task[] = [
  { ...tasks[0], id: "leaves-history", time: "Completed July 28" },
  { ...tasks[1], id: "boxes-history", time: "Completed July 21" },
  { ...tasks[2], id: "tablet-history", time: "Completed July 16" },
];

export const modeMeta: Record<
  TaskMode,
  { label: string; shortLabel: string; icon: Icon; color: string }
> = {
  paid: { label: "Paid task", shortLabel: "Paid", icon: Tag, color: "teal" },
  community: { label: "Community Help", shortLabel: "Volunteer", icon: HandHeart, color: "blue" },
  sponsored: { label: "Sponsored", shortLabel: "Sponsored", icon: Sparkle, color: "purple" },
};

